### ISSUE TITLE
Errorsoft.cas does not work as .tap

### ISSUE THREAD

**Issue by yqxq** [p2000t/M2000#102]
If you strip the header bloat from the errorsoft.cas and save it as .tap, M2000 throws garbage on screen when doing ZOEK, and programs won't run.

**Comment by dionoid** [comment]
Currently, if the first two bytes of a cassette file are $47 and $65, then it is assumed to be a 32-byte header.
Apparently that doesn't work for the Errorsoft tape, as that starts with a machinecode program, which has bogus values in these first two bytes, because machinecode programs use the 22nd and 23th bytes in the header as load address.
