### ISSUE TITLE
Make default window smaller (Allegro version)

### ISSUE THREAD

**Issue by dionoid** [p2000t/M2000#47]
Currently the Allegro version starts with a 960x720 window. On some older computers use a 1024x768 display, for which a smaller default window would be better.

**Comment by yqxq** [comment]
I think the text rendering weird/a little fat, can also be caused by the 720 resolution. I found that rendering is cleaner at 480 height or 960 height. So maybe default to 640x480.
1920x1440 is cleanest, and works great on QHD displays like 2560x1440. The resolution allows all interpolated half-pixels to be exactly 4:3 screen pixels so all diagonals in text are free from "jaggies".
Would it be an option to render 1920x1440 and downsample bilinear to the desired resolution?
Downsampling works cleanest to nearest integer values, like 240x320, 480x640, 720x960, 960x1280, leaving extra window space around it black. This is how many modern emutors work as well.

**Comment by yqxq** [comment]
Here you can see how clean these 5 resolutions render from a 1920x1440 native image. All are downsampled bilinear. Zoom in to see how the subsampling has very little effect on sharpness, and in every situation 1 direction is perfect integer scaling.
![1920x1440 (native)](https://github.com/p2000t/M2000/assets/145245534/1ca547df-2406-4d16-adff-6a622e7897fb)
![640x480](https://github.com/p2000t/M2000/assets/145245534/ac197cbd-259b-4e8b-ab66-0946a5d48ee5)
![960x720](https://github.com/p2000t/M2000/assets/145245534/c82bc0d2-bd94-4973-80db-70dfdc1b8b15)
![320x240](https://github.com/p2000t/M2000/assets/145245534/156aab7c-ae70-450a-9c5a-45a151037dd8)
![1440x1080](https://github.com/p2000t/M2000/assets/145245534/fc2cb135-ca14-4291-85fb-c1766abee222)
![1280x960](https://github.com/p2000t/M2000/assets/145245534/96e7a6d5-577d-49dc-893c-6a8375da8e76)
